<?php
return [
    "errmode" => [
        "silent" => PDO::ERRMODE_SILENT,
        "warning" => PDO::ERRMODE_WARNING,
        "exception" => PDO::ERRMODE_EXCEPTION,
    ],
    "case" => [
        "natural" => PDO::CASE_NATURAL,
        "upper" => PDO::CASE_UPPER,
        "lower" => PDO::CASE_LOWER,
    ],
    "fetch" => [
        "assoc" => PDO::FETCH_ASSOC,
        "obj" => PDO::FETCH_OBJ,
    ],
    "nulls" => [
        "natural" => PDO::NULL_NATURAL,
        "empty" => PDO::NULL_EMPTY_STRING,
        "to_string" => PDO::NULL_TO_STRING,
    ],
    "default" => "oracle",
    "oracle" => [
        "development" => [
            "driver"      => "oci",
            "dbname"      => "",
            "host"        => "",
            "port"        => "1521",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
        "ratify" => [
            "driver"      => "oci",
            "dbname"      => "",
            "host"        => "",
            "port"        => "1521",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
        "production" => [
            "driver"      => "oci",
            "dbname"      => "",
            "host"        => "",
            "port"        => "1521",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
    ],
    "mysql" => [
        "development" => [
            "driver"      => "mysql",
            "dbname"      => "",
            "host"        => "localhost",
            "port"        => "3306",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8mb4",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
        "ratify" => [
            "driver"      => "mysql",
            "dbname"      => "",
            "host"        => "localhost",
            "port"        => "3306",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8mb4",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
        "production" => [
            "driver"      => "mysql",
            "dbname"      => "",
            "host"        => "localhost",
            "port"        => "3306",
            "username"    => "",
            "password"    => "",
            "charset"     => "utf8mb4",
            "collation"   => "utf8mb4_unicode_ci",
            "prefix"      => "",
            "strict"      => false,
            "engine"      => null,
        ],
    ],
];
