version: '2'

volumes:
 mysql57_data:

services:         
 mysql57:
  image: mysql:5.7
  network_mode: bridge
  cpu_shares: 128
  mem_reservation: 128m
  mem_limit: 256m
  memswap_limit: -1
  privileged: true
  restart: unless-stopped
  container_name: mysql57-container
  hostname: mysql57
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: 123456
  volumes:
   - mysql57_data:/var/lib/mysql
