version: "2"

volumes:
  mysql_data:

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        hostname: mysql        
        ports:
            - "3306:3306"
        expose:
            - 3306
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: slimdb
        network_mode: "bridge"
    php:
        build: ./config/php/
        container_name: php7
        restart: always
        hostname: php7        
        ports:
            - "9000:9000"
        labels:
            - "traefik.enable=true"            
        volumes:
            - ./www:/var/www
        depends_on:
            - mysql
        links:
            - mysql
        network_mode: "bridge"
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        hostname: nginx        
        ports:
            - "8080:80"
        labels:
        - "traefik.enable=true"
        - "traefik.backend=api"
        # - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:localhost;PathPrefixStrip:/api"
        # - "traefik.frontend.rule=Host:tiete.manaus.am.gov.br;PathPrefixStrip:/api"
        - "traefik.port=80"            
        volumes:
            - ./config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
            - /tmp:/var/www/logs
        depends_on:
            - php
        links:
            - php
        network_mode: "bridge"
